### ISSUE TITLE
Create this as an npm module

### ISSUE THREAD

**Issue by lewisdonovan** [heysagnik/Linkees#21]
Are there any plans to make this available as an NPM module? It's so much quicker/easier/more normal to install via NPM/Yarn instead of having to fork and clone, you'd get way more downloads.

**Comment by heysagnik** [comment]
Nice idea ☺️👍 could you please help me to create it

**Comment by taksuparth** [comment]
Hey @heysagnik! I can pick this up

**Comment by heysagnik** [comment]
@taksuparth assigned you  :) 
Best of luck
Happy Hacking

**Comment by taksuparth** [comment]
linkees@1.0.0
