### ISSUE TITLE
Dockerize Linkees

### ISSUE THREAD

**Issue by hakimzuldev** [heysagnik/Linkees#25]
Hi @heysagnik, I believe there are developers out there would love to use Docker to run this application like me. I've managed to create two Dockerfiles - Development and Production as well as .dockerignore. 

I tested the the Docker Images on both my local and my server and it works. I would love to contribute my work to this project.

Cheers!

**Comment by heysagnik** [comment]
I have no idea regarding Docker, I want to discuss with you
Can you DM me?

**Comment by hakimzuldev** [comment]
Yes, sure. Would love to collaborate.

**Comment by hakimzuldev** [comment]
I've create a pull request for this issue #26

**Comment by hakimzuldev** [comment]
Thanks to @heysagnik for allowing me to contribute.
