### ISSUE TITLE
Update `package/Linkees` readme

### ISSUE THREAD

**Issue by taksuparth** [heysagnik/Linkees#29]
**Describe the bug**
Update `package/Linkees` readme

**Expected behavior**
This read-me file is shown on npm package page. (https://www.npmjs.com/package/linkees) 
- How to use section needs to be updated
- Docker file description is no longer required

**Comment by heysagnik** [comment]
Okay can you do it ?

**Comment by taksuparth** [comment]
@heysagnik I can do it, but not very good at documenting. It would be good if you can pick this up.

**Comment by heysagnik** [comment]
> @heysagnik I can do it, but not very good at documenting. It would be good if you can pick this up.

Hey can you do it please, You write , I will modify if needed ? 😅
At least provide me details how to use this module

**Comment by taksuparth** [comment]
sure, @heysagnik I'll add
