### ISSUE TITLE
Setup Linkees

### ISSUE THREAD

**Issue by Kush238** [heysagnik/Linkees#56]
Can you add the whole setup? Because new coders can also know how to setup the project from the start to end.

**Comment by heysagnik** [comment]
OK will do the needful

**Comment by ByNetsky** [comment]
It would be useful to add the dependencies or a more detailed description for "_npm install --save linkees_" or "_npm i react_" as this often leads to audit errors.
I am very rusty with React and was of the opinion that it was easier to build with your repo back then earlier.

**Comment by taksuparth** [comment]
@ByNetsky @heysagnik I was thinking we should make it super simple using npx. 
Just like `create-react-app`, you add one command, and it will ask for the information required to render the profile page and rest of the code will be automatically generated.

**Comment by heysagnik** [comment]
Yeah this is much better

> @ByNetsky @heysagnik I was thinking we should make it super simple using npx. Just like `create-react-app`, you add one command, and it will ask for the information required to render the profile page and rest of the code will be automatically generated.

**Comment by Bashamega** [comment]
> @ByNetsky @heysagnik I was thinking we should make it super simple using npx. Just like `create-react-app`, you add one command, and it will ask for the information required to render the profile page and rest of the code will be automatically generated.

I can create a bat file that will automatically set up the repository install the dependencies and even open the website.

**Comment by heysagnik** [comment]
> > @ByNetsky @heysagnik I was thinking we should make it super simple using npx. Just like `create-react-app`, you add one command, and it will ask for the information required to render the profile page and rest of the code will be automatically generated.
> 
> I can create a bat file that will automatically set up the repository install the dependencies and even open the website.

Proceed

**Comment by Bashamega** [comment]
> > > @ByNetsky @heysagnik I was thinking we should make it super simple using npx. Just like `create-react-app`, you add one command, and it will ask for the information required to render the profile page and rest of the code will be automatically generated.
> > 
> > 
> > I can create a bat file that will automatically set up the repository install the dependencies and even open the website.
> 
> Proceed

Assign me
